name: "Build"
on:
  pull_request:
    branches:
    - clean
  push:
    branches:
    - clean
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: constropt
        extraPullNames: cosette
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config --show-trace
    - run: nix flake check
